version: '3.7'

services:
  api:
    container_name: checkout-api
    image: node:16.13.2-alpine3.15
    working_dir: /app
    command: npm run start:dev
    expose:
      - '${PORT}'
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      checkout:
        aliases:
          - checkout-api
  pg:
    container_name: checkout-pg
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - checkout

networks:
  checkout:
    name: checkout
    driver: bridge
