version: '3.7'

services:
  api:
    container_name: ecommerce-api
    image: node:16.13.2-alpine3.15
    working_dir: /app
    command: npm run start:dev
    expose:
      - '${PORT}'
    ports:
      - '${PORT}:${PORT}'
      - 9229:9229
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      ecommerce:
        aliases:
          - ecommerce-api
  pg:
    container_name: ecommerce-pg
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - ecommerce

networks:
  ecommerce:
    name: ecommerce
    driver: bridge
